package com.raw.khipu.main;

import com.raw.khipu.KhipuAppUI;
import com.raw.khipu.dto.Property;
import com.raw.khipu.i18n.AppMessages;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnHeaderMode;
import com.vaadin.ui.VerticalLayout;

public class SideBarViewImpl extends CustomComponent {

  private static final long serialVersionUID = 11611656746243168L;
  @AutoGenerated
  private VerticalLayout mainLayout;
  private SideBarModel modelSideBar;
  private Table tabProperties;
  private KhipuAppUI app;
  private Accordion ac;
  private VerticalLayout tab1;
  private VerticalLayout tab2;
  private VerticalLayout tab3;
  private VerticalLayout tab4;

  public SideBarViewImpl() {
    buildMainLayout();
    setCompositionRoot(mainLayout);
  }

  @AutoGenerated
  private void buildMainLayout() {
    mainLayout = new VerticalLayout();
    ac = new Accordion();

    tab1 = new VerticalLayout();
    tabProperties = new Table();
    tabProperties.setPageLength(8);
    tabProperties.setColumnHeaderMode(ColumnHeaderMode.HIDDEN);
    tabProperties.setSizeFull();
    tab1.addComponent(tabProperties);
    tab1.setSizeFull();

    tab2 = new VerticalLayout();
    tab2.setMargin(true);
    GridLayout bookmark = new GridLayout(3, 3);
    Button btn1 = new Button();
    btn1.setIcon(FontAwesome.DESKTOP);
    btn1.setStyleName("raw-button-image");
    Button btn2 = new Button();
    btn2.setIcon(FontAwesome.YOUTUBE);
    btn2.setStyleName("raw-button-image");
    Button btn3 = new Button();
    btn3.setIcon(FontAwesome.APPLE);
    btn3.setStyleName("raw-button-image");
    Button btn4 = new Button();
    btn4.setIcon(FontAwesome.TWITTER);
    btn4.setStyleName("raw-button-image");
    Button btn5 = new Button();
    btn5.setIcon(FontAwesome.SPOTIFY);
    btn5.setStyleName("raw-button-image");
    Button btn6 = new Button();
    btn6.setIcon(FontAwesome.LINKEDIN);
    btn6.setStyleName("raw-button-image");
    Button btn7 = new Button();
    btn7.setIcon(FontAwesome.WEIBO);
    btn7.setStyleName("raw-button-image");
    Button btn8 = new Button();
    btn8.setIcon(FontAwesome.FLICKR);
    btn8.setStyleName("raw-button-image");
    Button btn9 = new Button();
    btn9.setIcon(FontAwesome.GOOGLE);
    btn9.setStyleName("raw-button-image");
    bookmark.addComponent(btn1, 0, 0);
    bookmark.addComponent(btn2, 1, 0);
    bookmark.addComponent(btn3, 2, 0);
    bookmark.addComponent(btn4, 0, 1);
    bookmark.addComponent(btn5, 1, 1);
    bookmark.addComponent(btn6, 2, 1);
    bookmark.addComponent(btn7, 0, 2);
    bookmark.addComponent(btn8, 1, 2);
    bookmark.addComponent(btn9, 2, 2);
    bookmark.setSizeFull();

    tab2.setSizeFull();
    tab2.addComponent(bookmark);
    tab2.setComponentAlignment(bookmark, Alignment.MIDDLE_CENTER);

    tab3 = new VerticalLayout();
    tab3.setMargin(true);
    tab3.addComponent(new Label("No implemented"));
    tab3.setSizeFull();

    tab4 = new VerticalLayout();
    tab4.setMargin(true);
    tab4.addComponent(new Label("No implemented"));
    tab4.setSizeFull();

    ac.addTab(tab1, "Parametros", FontAwesome.TABLE);
    ac.addTab(tab2, "Favoritos", FontAwesome.BOOKMARK);
    ac.addTab(tab3, "Mensajes", FontAwesome.COMMENT);
    ac.addTab(tab4, "Alertas", FontAwesome.BELL);

    ac.setSelectedTab(tab2);
    ac.setSizeFull();

    mainLayout.addComponent(ac);
  }

  public SideBarModel getModelSideBar() {
    return modelSideBar;
  }

  public void setModelSideBar(SideBarModel modelSideBar) {
    this.modelSideBar = modelSideBar;
  }

  public KhipuAppUI getApp() {
    return app;
  }

  public void setApp(KhipuAppUI app) {
    this.app = app;
  }

  public void populate() {
    BeanItemContainer<Property> propertyBeanItemContainer = new BeanItemContainer<Property>(
        Property.class);
    propertyBeanItemContainer.addAll(modelSideBar.getProperties());
    tabProperties.setContainerDataSource(propertyBeanItemContainer);
    init();
  }

  public void init() {
    ac.getTab(tab1).setCaption(app.getMessageLocale(AppMessages.AppSideBarParameters));
    ac.getTab(tab2).setCaption(app.getMessageLocale(AppMessages.AppSideBarBookmarks));
    ac.getTab(tab3).setCaption(app.getMessageLocale(AppMessages.AppSideBarMessages));
    ac.getTab(tab4).setCaption(app.getMessageLocale(AppMessages.AppSideBarAlerts));
  }
}
