package com.raw.khipu.util;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Window;

public class FontAwesomePallete extends CustomComponent {

  private static final long serialVersionUID = 7552060412141460774L;
  @AutoGenerated
  private Window window;

  public FontAwesomePallete() {
  }

  public Window getWindow() {
    window = new Window();
    int cols = 7;
    int rows = 300;
    int c = 0;
    int f = 0;

    GridLayout matrix = new GridLayout(cols, rows);
    FontAwesome[] fonts = FontAwesome.values();

    for (int i = 0; i < fonts.length; i++) {
      Button btn = new Button(fonts[i].name());
      btn.setIcon(fonts[i]);
      btn.setWidth("180px");
      matrix.addComponent(btn, c, f);
      if (c < cols - 1) {
        c = c + 1;
      } else {
        c = 0;
        f++;
      }
    }

    window.setContent(matrix);
    window.setSizeFull();
    return window;
  }

}
