package com.raw.khipu.login;

import java.util.ArrayList;
import java.util.List;

import com.raw.khipu.KhipuAppUI;
import com.raw.khipu.i18n.AppMessages;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class RestoreAccountViewImpl extends CustomComponent implements RestoreAccountView,
    ClickListener, View {

  private static final long serialVersionUID = 1861162081357937048L;
  @AutoGenerated
  private VerticalLayout mainLayout;
  private KhipuAppUI app;
  private final String ITEM_WIDTH = "275px";
  private final String BUTTON_WIDTH = "100px";
  private TextField txtEmail = new TextField("Email");
  private Button btnSend = new Button("Send", this);
  private Button btnSignIn = new Button("Sign in", this);

  public RestoreAccountViewImpl(KhipuAppUI _app) {
    this.app = _app;
    buildMainLayout();
    setCompositionRoot(mainLayout);
    setSizeFull();
  }

  @AutoGenerated
  private VerticalLayout buildMainLayout() {
    mainLayout = new VerticalLayout();

    Label lblProduct = new Label(app.getMessageLocale(AppMessages.AppProduct));
    lblProduct.setStyleName("raw-product-title");
    lblProduct.setSizeUndefined();
    mainLayout.addComponent(lblProduct);
    mainLayout.setExpandRatio(lblProduct, 1);
    mainLayout.setComponentAlignment(lblProduct, Alignment.MIDDLE_CENTER);

    VerticalLayout itemsLayout = new VerticalLayout();
    itemsLayout.setStyleName("raw-background-color");
    itemsLayout.setSpacing(true);
    itemsLayout.setMargin(true);

    Label txtTitleForm = new Label(app.getMessageLocale(AppMessages.UserRestoreAccount));
    txtTitleForm.setStyleName("raw-title");
    txtTitleForm.setSizeUndefined();
    txtEmail.setCaption(app.getMessageLocale(AppMessages.UserMail));
    txtEmail.setWidth(ITEM_WIDTH);
    txtEmail.addStyleName("inline-icon");
    txtEmail.setIcon(FontAwesome.ENVELOPE);
    txtEmail.setCursorPosition(1);
    btnSend.setCaption(app.getMessageLocale(AppMessages.btnSend));
    btnSend.setData("btnSend");
    btnSend.setWidth(BUTTON_WIDTH);

    btnSignIn.setCaption(app.getMessageLocale(AppMessages.LoginButton));
    btnSignIn.setData("btnSignIn");
    btnSignIn.setWidth(BUTTON_WIDTH);

    Image mainImage = (app.getMainImage());
    mainImage.setHeight("310px");
    mainImage.setWidth("450px");
    mainImage.setSizeUndefined();

    itemsLayout.addComponent(mainImage);
    itemsLayout.setComponentAlignment(mainImage, Alignment.MIDDLE_CENTER);
    itemsLayout.addComponent(txtTitleForm);
    itemsLayout.addComponent(txtEmail);
    itemsLayout.addComponent(btnSend);
    itemsLayout.addComponent(btnSignIn);
    itemsLayout.setComponentAlignment(btnSignIn, Alignment.MIDDLE_CENTER);
    itemsLayout.addComponent(new Label(app.getMessageLocale(AppMessages.UserRestoreDescription)));

    VerticalLayout rigthSide = new VerticalLayout();
    rigthSide.setSizeFull();
    VerticalLayout leftSide = new VerticalLayout();
    leftSide.setSizeFull();

    HorizontalLayout formLayout = new HorizontalLayout();
    formLayout.setStyleName("raw-background-color");
    formLayout.addComponent(rigthSide);
    formLayout.setExpandRatio(rigthSide, 1);
    formLayout.addComponent(itemsLayout);
    formLayout.setExpandRatio(itemsLayout, 1);
    formLayout.addComponent(leftSide);
    formLayout.setExpandRatio(leftSide, 1);
    formLayout.setSizeFull();

    mainLayout.addComponent(formLayout);
    mainLayout.setComponentAlignment(formLayout, Alignment.MIDDLE_CENTER);
    mainLayout.setExpandRatio(formLayout, 3);
    mainLayout.setImmediate(false);
    mainLayout.setSizeFull();

    return mainLayout;
  }

  @Override
  public void enter(ViewChangeEvent event) {

  }

  List<RestoreAccountViewListener> listeners = new ArrayList<RestoreAccountViewListener>();

  @Override
  public void addListener(RestoreAccountViewListener listener) {
    listeners.add(listener);
  }

  @Override
  public void buttonClick(ClickEvent event) {
    for (RestoreAccountViewListener listener : listeners) {
      listener.buttonClick(event.getButton().getData().toString(), txtEmail.getValue());
    }

  }

  @Override
  public void showSucceedMessage() {
    Notification.show(app.getMessageLocale(AppMessages.RestoreAccountSuccessMessage) + " "
        + txtEmail.getValue(), "", Notification.Type.HUMANIZED_MESSAGE);
  }

  @Override
  public void showFailureMessage() {
    Notification.show("Error: ", app.getMessageLocale(AppMessages.RestoreAccountFailureMessage),
        Notification.Type.ERROR_MESSAGE);
  }

  @Override
  public KhipuAppUI getUIApp() {
    return app;
  }

}
